env:
    token: "5172715354:AAGpEs0NkY9ALIa4G964q70hPcETXsxEEB"
    chat_id: "-1001749428852"
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: z4nyx/docker:latest
      cpu: 8
      memory: 32G

  Build_script:
      - git clone --depth=1 -b 4.19-rebase https://github.com/xenxynon/kernel_xiaomi_sdm660-4.19 lv && cd lv
      - bash .circleci/build
